// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSchoolAPI.Data;

#nullable disable

namespace SmartSchoolAPI.Migrations
{
    [DbContext(typeof(SmartSchoolDbContext))]
    partial class SmartSchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSchoolAPI.Entities.AcademicProgram", b =>
                {
                    b.Property<int>("AcademicProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcademicProgramId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registration_open");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("AcademicProgramId")
                        .HasName("pk_academic_programs");

                    b.ToTable("academic_programs", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("announcement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int?>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("TargetScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_scope");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId")
                        .HasName("pk_announcements");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_announcements_academic_program_id");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_announcements_classroom_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_announcements_course_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_announcements_created_by_user_id");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ArchivedClassroom", b =>
                {
                    b.Property<int>("ArchivedClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("archived_classroom_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArchivedClassroomId"));

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OriginalClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("original_classroom_id");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("program_name");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("teacher_name");

                    b.HasKey("ArchivedClassroomId")
                        .HasName("pk_archived_classrooms");

                    b.ToTable("archived_classrooms", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ArchivedEnrollment", b =>
                {
                    b.Property<int>("ArchivedEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("archived_enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArchivedEnrollmentId"));

                    b.Property<int>("ArchivedClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_classroom_id");

                    b.Property<decimal?>("ExamGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("exam_grade");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("final_grade");

                    b.Property<decimal?>("PracticalGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("practical_grade");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("student_name");

                    b.Property<string>("StudentNationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_national_id");

                    b.HasKey("ArchivedEnrollmentId")
                        .HasName("pk_archived_enrollments");

                    b.HasIndex("ArchivedClassroomId")
                        .HasDatabaseName("ix_archived_enrollments_archived_classroom_id");

                    b.ToTable("archived_enrollments", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ChatConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_conversations_user_id");

                    b.ToTable("chat_conversations", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_chat_messages_conversation_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassroomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("ClassroomId")
                        .HasName("pk_classrooms");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_classrooms_course_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_classrooms_teacher_id");

                    b.ToTable("classrooms", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordinator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("price");

                    b.HasKey("CourseId")
                        .HasName("pk_courses");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_courses_academic_program_id");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("ix_courses_coordinator_id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_date");

                    b.Property<decimal?>("ExamGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("exam_grade");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("final_grade");

                    b.Property<decimal?>("PracticalGrade")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("practical_grade");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("pk_enrollments");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_enrollments_classroom_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollments_student_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.FailedStudent", b =>
                {
                    b.Property<int>("FailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("failure_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FailureId"));

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FailureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failure_date");

                    b.Property<decimal>("FinalGpa")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("final_gpa");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ProgramNameAtFailure")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("program_name_at_failure");

                    b.Property<int?>("StudentUserId")
                        .HasColumnType("integer")
                        .HasColumnName("student_user_id");

                    b.HasKey("FailureId")
                        .HasName("pk_failed_students");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_failed_students_academic_program_id");

                    b.ToTable("failed_students", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Graduation", b =>
                {
                    b.Property<int>("GraduationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("graduation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GraduationId"));

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<decimal?>("FinalGpa")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("final_gpa");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graduation_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<string>("ProgramNameAtGraduation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("program_name_at_graduation");

                    b.Property<int?>("StudentUserId")
                        .HasColumnType("integer")
                        .HasColumnName("student_user_id");

                    b.HasKey("GraduationId")
                        .HasName("pk_graduations");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_graduations_academic_program_id");

                    b.ToTable("graduations", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.GraduationCertificate", b =>
                {
                    b.Property<int>("GraduationId")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_id");

                    b.Property<string>("CertificateUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("certificate_url");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_type");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("public_id");

                    b.HasKey("GraduationId")
                        .HasName("pk_graduation_certificates");

                    b.ToTable("graduation_certificates", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecture_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LectureOrder")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("LectureId")
                        .HasName("pk_lectures");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_lectures_classroom_id");

                    b.ToTable("lectures", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuiz", b =>
                {
                    b.Property<int>("LectureQuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureQuizId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("LectureId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("LectureQuizId")
                        .HasName("pk_lecture_quizzes");

                    b.HasIndex("LectureId")
                        .IsUnique()
                        .HasDatabaseName("ix_lecture_quizzes_lecture_id");

                    b.ToTable("lecture_quizzes", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizQuestion", b =>
                {
                    b.Property<int>("LectureQuizQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureQuizQuestionId"));

                    b.Property<string>("ImagePublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_public_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<int>("LectureQuizId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_id");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_type");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("LectureQuizQuestionId")
                        .HasName("pk_lecture_quiz_questions");

                    b.HasIndex("LectureQuizId")
                        .HasDatabaseName("ix_lecture_quiz_questions_lecture_quiz_id");

                    b.ToTable("lecture_quiz_questions", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizQuestionOption", b =>
                {
                    b.Property<int>("LectureQuizQuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_question_option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureQuizQuestionOptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("LectureQuizQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("LectureQuizQuestionOptionId")
                        .HasName("pk_lecture_quiz_question_options");

                    b.HasIndex("LectureQuizQuestionId")
                        .HasDatabaseName("ix_lecture_quiz_question_options_lecture_quiz_question_id");

                    b.ToTable("lecture_quiz_question_options", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizSubmission", b =>
                {
                    b.Property<int>("LectureQuizSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_submission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureQuizSubmissionId"));

                    b.Property<int>("LectureQuizId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("LectureQuizSubmissionId")
                        .HasName("pk_lecture_quiz_submissions");

                    b.HasIndex("LectureQuizId")
                        .HasDatabaseName("ix_lecture_quiz_submissions_lecture_quiz_id");

                    b.HasIndex("StudentId", "LectureQuizId")
                        .IsUnique()
                        .HasDatabaseName("ix_lecture_quiz_submissions_student_id_lecture_quiz_id");

                    b.ToTable("lecture_quiz_submissions", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_type");

                    b.Property<int?>("LectureId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_id");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_type");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("PublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("public_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("MaterialId")
                        .HasName("pk_materials");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_materials_course_id");

                    b.HasIndex("LectureId")
                        .HasDatabaseName("ix_materials_lecture_id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reset_code");

                    b.HasKey("UserId")
                        .HasName("pk_password_reset_tokens");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.PaymentSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .HasColumnType("integer")
                        .HasColumnName("settings_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AdminFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("admin_full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.HasKey("SettingsId")
                        .HasName("pk_payment_settings");

                    b.ToTable("payment_settings", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ProgramRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registration_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PaymentReceiptPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payment_receipt_public_id");

                    b.Property<string>("PaymentReceiptUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("payment_receipt_url");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RegistrationId")
                        .HasName("pk_program_registrations");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_program_registrations_academic_program_id");

                    b.ToTable("program_registrations", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("ImagePublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_public_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("question_type");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("QuestionId")
                        .HasName("pk_questions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_questions_course_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_questions_created_by_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_questions_reviewed_by_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.QuestionOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("question_option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionOptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("QuestionOptionId")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_options_question_id");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.StudentAnswer", b =>
                {
                    b.Property<int>("StudentAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_answer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentAnswerId"));

                    b.Property<int>("LectureQuizQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_question_id");

                    b.Property<int>("LectureQuizSubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_quiz_submission_id");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("selected_option_id");

                    b.HasKey("StudentAnswerId")
                        .HasName("pk_student_answers");

                    b.HasIndex("LectureQuizQuestionId")
                        .HasDatabaseName("ix_student_answers_lecture_quiz_question_id");

                    b.HasIndex("LectureQuizSubmissionId")
                        .HasDatabaseName("ix_student_answers_lecture_quiz_submission_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_student_answers_selected_option_id");

                    b.ToTable("student_answers", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AcademicProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_program_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("AcademicProgramId")
                        .HasDatabaseName("ix_users_academic_program_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.WeeklyChallengeSubmission", b =>
                {
                    b.Property<int>("WeeklyChallengeSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("weekly_challenge_submission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeeklyChallengeSubmissionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TimeTakenSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_taken_seconds");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer")
                        .HasColumnName("week_of_year");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("WeeklyChallengeSubmissionId")
                        .HasName("pk_weekly_challenge_submissions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_weekly_challenge_submissions_course_id");

                    b.HasIndex("StudentId", "CourseId", "Year", "WeekOfYear")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_challenge_submissions_student_id_course_id_year_week");

                    b.ToTable("weekly_challenge_submissions", (string)null);
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Announcement", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("AcademicProgramId")
                        .HasConstraintName("fk_announcements_academic_programs_academic_program_id");

                    b.HasOne("SmartSchoolAPI.Entities.Classroom", "Classroom")
                        .WithMany("Announcements")
                        .HasForeignKey("ClassroomId")
                        .HasConstraintName("fk_announcements_classrooms_classroom_id");

                    b.HasOne("SmartSchoolAPI.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_announcements_courses_course_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_announcements_users_created_by_user_id");

                    b.Navigation("AcademicProgram");

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ArchivedEnrollment", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.ArchivedClassroom", "ArchivedClassroom")
                        .WithMany("ArchivedEnrollments")
                        .HasForeignKey("ArchivedClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archived_enrollments_archived_classrooms_archived_classroom");

                    b.Navigation("ArchivedClassroom");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ChatConversation", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_conversations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ChatMessage", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Classroom", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Course", "Course")
                        .WithMany("Classrooms")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classrooms_courses_course_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Teacher")
                        .WithMany("TaughtClassrooms")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("fk_classrooms_users_teacher_id");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Course", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany("Courses")
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_academic_programs_academic_program_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_courses_users_coordinator_id");

                    b.Navigation("AcademicProgram");

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Enrollment", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Classroom", "Classroom")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_classrooms_classroom_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_student_id");

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.FailedStudent", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_failed_students_academic_programs_academic_program_id");

                    b.Navigation("AcademicProgram");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Graduation", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_graduations_academic_programs_academic_program_id");

                    b.Navigation("AcademicProgram");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.GraduationCertificate", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Graduation", "Graduation")
                        .WithOne("Certificate")
                        .HasForeignKey("SmartSchoolAPI.Entities.GraduationCertificate", "GraduationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_graduation_certificates_graduations_graduation_id");

                    b.Navigation("Graduation");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Lecture", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Classroom", "Classroom")
                        .WithMany("Lectures")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lectures_classrooms_classroom_id");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuiz", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Lecture", "Lecture")
                        .WithOne("LectureQuiz")
                        .HasForeignKey("SmartSchoolAPI.Entities.LectureQuiz", "LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecture_quizzes_lectures_lecture_id");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizQuestion", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.LectureQuiz", "LectureQuiz")
                        .WithMany("Questions")
                        .HasForeignKey("LectureQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecture_quiz_questions_lecture_quizzes_lecture_quiz_id");

                    b.Navigation("LectureQuiz");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizQuestionOption", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.LectureQuizQuestion", "LectureQuizQuestion")
                        .WithMany("Options")
                        .HasForeignKey("LectureQuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecture_quiz_question_options_lecture_quiz_questions_lectur");

                    b.Navigation("LectureQuizQuestion");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizSubmission", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.LectureQuiz", "LectureQuiz")
                        .WithMany("Submissions")
                        .HasForeignKey("LectureQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecture_quiz_submissions_lecture_quizzes_lecture_quiz_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecture_quiz_submissions_users_student_id");

                    b.Navigation("LectureQuiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Material", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_materials_courses_course_id");

                    b.HasOne("SmartSchoolAPI.Entities.Lecture", "Lecture")
                        .WithMany("Materials")
                        .HasForeignKey("LectureId")
                        .HasConstraintName("fk_materials_lectures_lecture_id");

                    b.Navigation("Course");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ProgramRegistration", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany("ProgramRegistrations")
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_registrations_academic_programs_academic_program_id");

                    b.Navigation("AcademicProgram");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Question", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_courses_course_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_users_created_by_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questions_users_reviewed_by_id");

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.QuestionOption", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.StudentAnswer", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.LectureQuizQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("LectureQuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_answers_lecture_quiz_questions_lecture_quiz_questio");

                    b.HasOne("SmartSchoolAPI.Entities.LectureQuizSubmission", "Submission")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("LectureQuizSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_answers_lecture_quiz_submissions_lecture_quiz_submi");

                    b.HasOne("SmartSchoolAPI.Entities.LectureQuizQuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_answers_lecture_quiz_question_options_selected_opti");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.User", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany("Users")
                        .HasForeignKey("AcademicProgramId")
                        .HasConstraintName("fk_users_academic_programs_academic_program_id");

                    b.Navigation("AcademicProgram");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.WeeklyChallengeSubmission", b =>
                {
                    b.HasOne("SmartSchoolAPI.Entities.Course", "Course")
                        .WithMany("WeeklyChallengeSubmissions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_challenge_submissions_courses_course_id");

                    b.HasOne("SmartSchoolAPI.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_challenge_submissions_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.AcademicProgram", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("ProgramRegistrations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ArchivedClassroom", b =>
                {
                    b.Navigation("ArchivedEnrollments");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Classroom", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Course", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Materials");

                    b.Navigation("Questions");

                    b.Navigation("WeeklyChallengeSubmissions");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Graduation", b =>
                {
                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Lecture", b =>
                {
                    b.Navigation("LectureQuiz");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.LectureQuizSubmission", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SmartSchoolAPI.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TaughtClassrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
